#!/usr/bin/expect

set timeout 1000

set host [lindex $argv 0]

set password [lindex $argv 1]

set excmd [lrange $argv 2 10000]

spawn ssh "$host"
 
expect  "*password:" 

send "$password\r"

expect "*bash*"

send "$excmd \r"

interact

